### PR TITLE
#508 Unhandled System.ArgumentException and

### LINKED ISSUE #508: Unhandled System.ArgumentException in LoadCachedAnalysis
```
<entry>
    <record>96225</record>
    <time>2015/10/05 18:02:16.567</time>
    <type>Error</type>
    <source>Node.js Tools for Visual Studio</source>
    <description>
	Unhandled exception in LoadCachedAnalysis (F:\72\src\Nodejs\Product\Nodejs\Intellisense\VsProjectAnalyzer.cs:1404);
	System.ArgumentException: Source array was not long enough. Check srcIndex and length, and the array's lower;   
	at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable);   
	at Microsoft.NodejsTools.Analysis.Deque`1.GrowArray();   
	at Microsoft.NodejsTools.Analysis.Deque`1.Append(T x);   
	at Microsoft.NodejsTools.Analysis.AnalysisLog.Add(String Event, Object[] Args);   
	at Microsoft.NodejsTools.Analysis.AnalysisLog.NewUnit(AnalysisUnit unit);   
	at Microsoft.NodejsTools.Analysis.AnalysisUnit..ctor(Statement ast, JsAst tree, EnvironmentRecord environment);   
	at Microsoft.NodejsTools.Analysis.JsAnalyzer.&lt;&gt;c__DisplayClass30_1.&lt;AddPackageJson&gt;b__0(String dependency);   
	at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext();   
	at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection);   
	at Microsoft.NodejsTools.Analysis.JsAnalyzer.AddPackageJson(String filePath, String entryPoint, List`1 dependencies);   
	at Microsoft.NodejsTools.Intellisense.VsProjectAnalyzer.AddPackageJson(String path, String mainFile, List`1 dependencies);   
	at Microsoft.NodejsTools.Intellisense.VsProjectAnalyzer.&lt;&gt;c__DisplayClass55_0.&lt;AddPackageJson&gt;b__0();   
	at Microsoft.NodejsTools.Intellisense.VsProjectAnalyzer.&lt;&gt;c__DisplayClass108_2.&lt;LoadCachedAnalysis&gt;b__0();   
	at System.Threading.Tasks.Task.InnerInvoke();   
	at System.Threading.Tasks.Task.Execute();
	--- End of stack trace from previous location where exception was thrown ---;   
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task);   
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task);   
	at Microsoft.VisualStudioTools.VsTaskExtensions.&lt;HandleAllExceptions&gt;d__4.MoveNext()
	</description>
  </entry>
```

### PR DESCRIPTION
**Pull request by mousetraps**
System.IndexOutOfRangeException during LoadCachedAnalysis
- We were simultaneously mutating the AnalysisLog from two threads. This
  caused various Deque properties like _data, _tail, etc. to get out of
  sync with one another. The fix is to lock LogItems whenever adding new
  events to the log.

fix #508

### CODE REVIEW

**Comment by billti** [comment]
:+1:

File: Nodejs/Product/Analysis/Analysis/AnalysisLog.cs [hunk 1]
```diff
@@ -87,17 +87,19 @@ struct LogItem {
             int max = MaxItems;
 
             if (max != 0) {
-                if (LogItems.Count >= max) {
-                    while (LogItems.Count > max) {
-                        // if the queue was set to shrink remove any old items.
-                        LogItems.PopLeft();
+                lock (LogItems) {
```
Comment (mousetraps) [inline Nodejs/Product/Analysis/Analysis/AnalysisLog.cs]: I'll find a way to do this without locking, so it doesn't reduce performance

**Comment by mousetraps** [comment]
Removed the locking behavior and added some comments. Instead we now just create RequireAnalysisUnits on the analysis thread.
