### PR TITLE
Fix Repl window null deref when main NTVS package has not been loaded yet

### LINKED ISSUE #917: Null Dereference when Using Interactive Window Before Main NodeJs Package is loaded
**Repo**

1. Launch VS (restored state should have Node.js interactive window open already)
1. Quickly type something into the interactive window
1. Press enter.

**Expected**
Repl stuff

**Actual**
Null deref in GetStartupProject:

```
>	Microsoft.NodejsTools.dll!Microsoft.VisualStudioTools.CommonPackage.GetStartupProject(System.IServiceProvider serviceProvider) Line 178	C#
 	Microsoft.NodejsTools.dll!Microsoft.NodejsTools.Repl.VsNodejsReplSite.GetStartupProject() Line 26	C#
 	Microsoft.NodejsTools.dll!Microsoft.NodejsTools.Repl.NodejsReplEvaluator.GetNodeExePath() Line 228	C#
 	Microsoft.NodejsTools.dll!Microsoft.NodejsTools.Repl.NodejsReplEvaluator.Connect() Line 180	C#
 	Microsoft.NodejsTools.dll!Microsoft.NodejsTools.Repl.NodejsReplEvaluator.EnsureConnected() Line 169	C#
 	Microsoft.NodejsTools.dll!Microsoft.NodejsTools.Repl.NodejsReplEvaluator.ExecuteText(string text) Line 135	C#
 	Microsoft.NodejsTools.InteractiveWindow.dll!Microsoft.NodejsTools.Repl.ReplWindow.ExecuteActiveCode.AnonymousMethod__196_0() Line 2330	C#
 	Microsoft.NodejsTools.InteractiveWindow.dll!Microsoft.NodejsTools.Repl.ReplWindow.UIThread(System.Action action) Line 3272	C#
 	Microsoft.NodejsTools.InteractiveWindow.dll!Microsoft.NodejsTools.Repl.ReplWindow.ExecuteActiveCode() Line 2299	C#
 	Microsoft.NodejsTools.InteractiveWindow.dll!Microsoft.NodejsTools.Repl.ReplWindow.Submit() Line 1943	C#
 	Microsoft.NodejsTools.InteractiveWindow.dll!Microsoft.NodejsTools.Repl.ReplWindow.PreEditorCommandFilterExec(ref System.Guid pguidCmdGroup, uint nCmdID, uint nCmdexecopt, System.IntPtr pvaIn, System.IntPtr pvaOut) Line 1567	C#
 	Microsoft.NodejsTools.InteractiveWindow.dll!Microsoft.NodejsTools.Repl.ReplWindow.CommandFilter.Exec(ref System.Guid pguidCmdGroup, uint nCmdID, uint nCmdexecopt, System.IntPtr pvaIn, System.IntPtr pvaOut) Line 1344	C#
```

The root cause is that `NodejsPackage.Instance` is null at this point.

This crashes the interactive window and requires a VS restart.

### PR DESCRIPTION
**Pull request by mjbvz**
#917

**Bug**
If the Repl window is used before the main NTVS package has been loaded, `NodeJsPacakge.Instance` will be null. This causes a null deref problem in some call paths (see #917)

**Fix**
Add a few null checks to these call paths.

closes #917

### CODE REVIEW

**Comment by mjbvz** [comment]
Actually, the change should not hurt anything, but it also does not solve a normal use case bug.

During development, I was messing around with the Repl window and this ended up persisting some bad data about the Repl Window to the registry under the `ActiveRepls` key. This seemed to have messed up loading, causing this bug to be hit. In normal user flows, I think that `Node.Instance` should always be set at these points in the code.

File: Common/Product/SharedProject/CommonPackage.cs [hunk 1]
```diff
@@ -129,6 +129,10 @@ public abstract class CommonPackage : Package, IOleComponent {
         /// </summary>
         /// <returns></returns>
         public static IWpfTextView GetActiveTextView(System.IServiceProvider serviceProvider) {
+            if (serviceProvider == null) {
+                return null;
+            }
```
Comment (mousetraps) [inline Common/Product/SharedProject/CommonPackage.cs]: for both null checks, it's okay to fail gracefully, but let's go ahead and also add a debug assert so we know something's up when the issue occurs.

**Comment by mousetraps** [comment]
minor comment and :+1: after that
