### PR TITLE
Fix for #684, null dereference for incomplete for loop analysis

### LINKED ISSUE #684: Inserting a newline in a JS file that has an ill-defined for loop throws an NRE
When I have a partially-defined `for` loop (shown below) followed by a close brace of any sort in a JS file, inserting a newline anywhere in the file throws a `NullReferenceException`. Example code:

```js
{
for(var
}
```

When I have a file with those contents open in VS and I enter a newline, I get the following exception (a summary is displayed in a message box, but I have copied the full trace from the output window):
```
2/12/2016 7:39:35 PM: An exception was thrown while executing command Std2K: RETURN:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.NodejsTools.Parsing.Declaration.set_Variables(VariableDeclaration[] value)
   at Microsoft.NodejsTools.Parsing.JSParser.ParseForStatement()
   at Microsoft.NodejsTools.Parsing.JSParser.ParseStatement()
   at Microsoft.NodejsTools.Parsing.JSParser.ParseBlock()
   at Microsoft.NodejsTools.Parsing.JSParser.ParseStatement()
   at Microsoft.NodejsTools.Parsing.JSParser.ParseStatements()
   at Microsoft.NodejsTools.Parsing.JSParser.Parse(CodeSettings settings)
   at Microsoft.NodejsTools.Formatting.Formatter.GetEdits(String code, FormattingOptions options, Boolean onEnter)
   at Microsoft.NodejsTools.Formatting.Formatter.GetEditsAfterEnter(String code, Int32 start, Int32 end, FormattingOptions options)
   at Microsoft.NodejsTools.EditFilter.FormatOnEnter(SnapshotPoint start, SnapshotPoint end)
   at Microsoft.NodejsTools.EditFilter.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.VisualStudio.Editor.PeekF1.CommandFilter.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at MadsKristensen.EditorExtensions.Commands.CommandExceptionFilter.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) in C:\projects\webessentials2015\EditorExtensions\Shared\Commands\CommandExceptionFilter.cs:line 30
```

I see mentions of both NTVS and Web Essentials (which I have installed) in the log, but given that the majority of the stack is in the `Microsoft.NodejsTools` namespace, I decided that this was likely the best place to start.

Platform info:
- Windows 10 Insider Preview build 14251 (Just to make your lives more complicated :wink:)
- Visual Studio 2015 Community -- Update 1
- Node.js Tools 1.1.31117.00

### PR DESCRIPTION
**Pull request by mjbvz**
Just adds a null check before setting parent on declarations.

closes #684

### CODE REVIEW

File: Nodejs/Product/Analysis/JavaScript/declaration.cs [hunk 1]
```diff
@@ -56,7 +56,8 @@ public override IEnumerable<Node> Children
 
             set {
                 for (int i = 0; i < value.Length; i++) {
-                    value[i].Parent = this;
+                    if (value[i] != null)
```
Comment (mousetraps) [inline Nodejs/Product/Analysis/JavaScript/declaration.cs]: Hrm, I don't believe any of the values there should ever be null. Looks like `ParseIdentifierInitializer` is returning null, and that value is not being null checked before being added to `varList` in `ParseForStatement`. Additionally, I don't believe we should be calling `UpdateWithOtherNode` unless `initializer` is not null. So instead of checking for null within , I think we should just do the proper null checks within `ParseForStatement` before adding it to the list.
* https://github.com/Microsoft/nodejstools/blob/master/Nodejs/Product/Analysis/JavaScript/jsparser.cs#L1111-L1112
* https://github.com/Microsoft/nodejstools/blob/master/Nodejs/Product/Analysis/JavaScript/jsparser.cs#L1119-L1120

@DinoV could you please confirm?

Comment (mousetraps) [inline Nodejs/Product/Analysis/JavaScript/declaration.cs]: Also, in general, please include braces with if statements (even if they are single-statement) because it keeps the code more readable and maintainable.

**Comment by mousetraps** [comment]
@mjbvz ping - would be great to merge this in for this next release.

**Comment by mjbvz** [comment]
Added the external null checks.

I believe we should keep the internal null check as well though, since a setter should never result in a null dereference like this.

File: Nodejs/Product/Analysis/JavaScript/declaration.cs [hunk 2]
```diff
@@ -56,7 +56,9 @@ public override IEnumerable<Node> Children
 
             set {
                 for (int i = 0; i < value.Length; i++) {
-                    value[i].Parent = this;
+                    if (value[i] != null) {
+                        value[i].Parent = this;
+                    }
```
Comment (mousetraps) [inline Nodejs/Product/Analysis/JavaScript/declaration.cs]: Keeping the internal null check means we could be hiding more systemic problems.

File: Nodejs/Product/Analysis/JavaScript/jsparser.cs [hunk 3]
```diff
@@ -22,6 +22,7 @@
 using System.Reflection;
 using System.Runtime.Serialization;
 using Microsoft.Ajax.Utilities;
+using System.Linq;
```
Comment (mousetraps) [inline Nodejs/Product/Analysis/JavaScript/jsparser.cs]: System before everything else.
