### PR TITLE
Only end the build if it started successfully

### LINKED ISSUE #2117: Don't end build if it failed to start
https://github.com/Microsoft/nodejstools/blob/2118e8ff4dcba7cfd281f8e9d12b62cc0d96ff0f/Nodejs/Product/Nodejs/SharedProject/ProjectNode.cs#L2625

If a build is in-progress, we throw an `InvalidOperationException`.  There's nothing inherently wrong with this, but we then try to end the build that never started (in the following finally block) and that call hangs forever since no build is in progress.

If we want to continue throwing an exception, the obvious workaround would be to add a flag tracking whether or not the build was actually started and only end it if the flag is set.

Repro: Open TypeScript-VisualStudio.sln with a VS build from the staging branch.

### PR DESCRIPTION
**Pull request by amcasey**
In the (rare) case that a design time build failed to start, we would
attempt to release the UI thread in `TryBeginBuild` and then again in
`EndBuild`.  The comments suggested that it was the `TryBeginBuild` that
was intended to do the cleanup and code inspection confirmed that
`EndBuild` did not perform useful work if `TryBeginBuild` failed, so
this change gives `TryBeginBuild` responsibility for cleanup and doesn't
call `EndBuild` a build was successfully started.

Fixes #2117 

Tested by manually inducing `TryBeginBuild` failures in the debugger.

### CODE REVIEW

File: Nodejs/Product/Nodejs/SharedProject/ProjectNode.cs [hunk 1]
```diff
@@ -2614,20 +2614,21 @@ protected virtual MSBuildResult InvokeMsBuild(string target)
...
-            try
+            // Do the actual Build
+            if (this.buildProject != null)
             {
-                // Do the actual Build
-                if (this.buildProject != null)
+                const bool designTime = true;
+                const bool requiresUIThread = true;
+
+                if (!TryBeginBuild(designTime, requiresUIThread))
```
Comment (armanio123) [inline Nodejs/Product/Nodejs/SharedProject/ProjectNode.cs]: Either `designTime` or `requiresUIThread` is not required. The two places where `TryBeginBuild` is called, have the same value for both variables. We can remove one and refactor the method to make it a little bit more readable. I suggest removing `designTime`, as `requiresUIThread` is easy to understand its purpose.

File: Nodejs/Product/Nodejs/SharedProject/ProjectNode.cs [hunk 2]
```diff
@@ -2647,10 +2648,10 @@ protected virtual MSBuildResult InvokeMsBuild(string target)
 
                     result = (buildResult.OverallResult == BuildResultCode.Success) ? MSBuildResult.Successful : MSBuildResult.Failed;
                 }
-            }
-            finally
-            {
-                EndBuild(submission, designTime, true);
+                finally
+                {
+                    EndBuild(submission, designTime, requiresUIThread);
```
Comment (armanio123) [inline Nodejs/Product/Nodejs/SharedProject/ProjectNode.cs]: Same comment as about `designTime` and `requiresUIThread`.

File: Nodejs/Product/Nodejs/SharedProject/ProjectNode.cs [hunk 3]
```diff
@@ -6026,57 +6028,44 @@ private void SetupProjectGlobalPropertiesThatAllProjectSystemsMustSet()
...
-            try
+            // If the SVsBuildManagerAccessor service is absent, we're not running within Visual Studio.
+            if (this.buildManagerAccessor != null)
             {
-                // If the SVsBuildManagerAccessor service is absent, we're not running within Visual Studio.
-                if (this.buildManagerAccessor != null)
+                if (requiresUIThread)
                 {
-                    if (requiresUIThread)
+                    var result = this.buildManagerAccessor.ClaimUIThreadForBuild();
```
Comment (armanio123) [inline Nodejs/Product/Nodejs/SharedProject/ProjectNode.cs]: Can `ClaimUIThreadForBuild` lock the UI thread and then throw and exception?

File: Nodejs/Product/Nodejs/SharedProject/ProjectNode.cs [hunk 4]
```diff
@@ -6026,57 +6028,44 @@ private void SetupProjectGlobalPropertiesThatAllProjectSystemsMustSet()
...
-                        releaseUIThread = true; // assume we need to release this immediately until we get through the whole gauntlet.
+                        // Not allowed to claim the UI thread right now. Try again later.
+                        return false;
                     }
+                }
 
-                    if (designTime)
+                if (designTime)
+                {
+                    var result = this.buildManagerAccessor.BeginDesignTimeBuild();
```
Comment (armanio123) [inline Nodejs/Product/Nodejs/SharedProject/ProjectNode.cs]: Can this throw an exception? If so, I think the UI thread will be blocked and never released.

File: Nodejs/Product/Nodejs/SharedProject/ProjectNode.cs (hunk 1 above)
Comment (amcasey) [reply Nodejs/Product/Nodejs/SharedProject/ProjectNode.cs]: I'd prefer to retain `designTime` since one could reasonably conclude that `designTime` requires the UI thread, but I don't see how would deduce that `requiresUIThread` implies a design time build.

File: Nodejs/Product/Nodejs/SharedProject/ProjectNode.cs (hunk 3 above)
Comment (amcasey) [reply Nodejs/Product/Nodejs/SharedProject/ProjectNode.cs]: I'm not sure what you mean by "lock the UI thread".  It sets a flag indicating that it's going to use the UI thread and that others checking the flag should not.

I would also not expect it to throw since it returns an HRESULT.  It can still throw OOM, etc, but such exceptions are unrecoverable anyway.

File: Nodejs/Product/Nodejs/SharedProject/ProjectNode.cs (hunk 4 above)
Comment (amcasey) [reply Nodejs/Product/Nodejs/SharedProject/ProjectNode.cs]: As above, I believe it's technically possible, but I'm not convinced we should attempt to recover if it does.

File: Nodejs/Product/Nodejs/SharedProject/ProjectNode.cs (hunk 1 above)
Comment (amcasey) [reply Nodejs/Product/Nodejs/SharedProject/ProjectNode.cs]: I'll do this in a new PR.
