### PR TITLE
#388 custom captions don't work with web publish

### LINKED ISSUE #388: NTVS 1.1 folder naming doesn't work with web publish
When folders are renamed from "public" to "public (browser)" or "public (node)" this breaks web publishing as it now publishes files to a "public (browser)" folder instead of "public".

### PR DESCRIPTION
**Pull request by mousetraps**
- The issue was that in some scenarios we were returning the caption,
  rather than the actual name of the file/folder

Fix #388

### CODE REVIEW

File: Common/Product/SharedProject/HierarchyNode.cs [hunk 1]
```diff
@@ -590,7 +590,7 @@ internal abstract class HierarchyNode :
                     break;
 
                 case __VSHPROPID.VSHPROPID_Name:
-                    result = this.Caption;
+                    result = CommonUtils.GetFileOrDirectoryName(this.Url);
```
Comment (billti) [inline Common/Product/SharedProject/HierarchyNode.cs]: If I look though this file for other uses for `this.caption`, then I see it used for `SaveName is the name shown in the Save and the Save Changes dialog boxes` and `GetEditLabel: Called by the shell to get the node caption when the user tries to rename from the GUI`, and `GetRelationalName`. Seems like all of these probably should be using the proper filename/url also, and not the labeled caption.

Comment (mousetraps) [inline Common/Product/SharedProject/HierarchyNode.cs]: Yeah, I can change those too - most of those (e.g. GetEditLabel) are overridden in NodejsFolderNode, but may as well fix it in HierarcyNode.

Comment (mousetraps) [inline Common/Product/SharedProject/HierarchyNode.cs]: Went ahead and updated references to Caption throughout the project system.
