### PR TITLE
Fix es5 buffer parser crash

### LINKED ISSUE #1018: REPL window throws ActivityLog error after switching from ES6->ES5
Using latest build from master (VS2015 U2, 6/11/2016)
1. had interactive window open
2. switched from ES6->ES5
3. started typing in interactive window
4. activity log error dialog pops up

Relevant ActivityLog entry:
```
System.ObjectDisposedException: Cannot access a disposed object. at
System.Threading.TimerQueueTimer.Change(UInt32 dueTime, UInt32 period) at
System.Threading.Timer.Change(Int32 dueTime, Int32 period) at
Microsoft.NodejsTools.Intellisense.VsProjectAnalyzer.BufferParser.BufferChangedLowPriority(Object sender, TextContentChangedEventArgs e) at
Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args)
```

### LINKED ISSUE #1020: VS Crash while using REPL
After ignoring activity log error in #1018, and typing another entry in the repl

Using latest build from master (VS2015 U2, 6/11/2016)
1. had interactive window open
2. switched from ES6->ES5
3. started typing in interactive window
4. activity log error dialog pops up
5. type another entry, press enter

EDIT: Just as in #1018, the same error occurs when switching from ES5->ES6
```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean ByRef)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(System.Runtime.InteropServices.SafeHandle, Boolean ByRef)
   at Microsoft.Win32.Win32Native.SetEvent(Microsoft.Win32.SafeHandles.SafeWaitHandle)
   at System.Threading.EventWaitHandle.Set()
   at Microsoft.NodejsTools.Intellisense.VsProjectAnalyzer+AnalysisQueue.Enqueue(Microsoft.NodejsTools.Analysis.IAnalyzable, Microsoft.NodejsTools.Intellisense.AnalysisPriority)
   at Microsoft.NodejsTools.Intellisense.VsProjectAnalyzer.ParseBuffers(BufferParser, Microsoft.VisualStudio.Text.ITextSnapshot[])
   at Microsoft.NodejsTools.Intellisense.VsProjectAnalyzer+BufferParser.ReparseWorker(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

```

### PR DESCRIPTION
**Pull request by mjbvz**
##### Bug
A callback is getting invoked on BufferParser after the BufferParser is disposed. The easiest way to trigger a dispose is by switching between ES6 and ES5 Intellisense

##### Fix
Unregister all callbacks in the dispose method and remove all buffers.

closes #1018 
closes #1020

### CODE REVIEW

**Comment by mjbvz** [comment]
I believe this may also fix #1020, that crash had a different callstack so I can't be sure. I haven't seen #1020 happen though after applying this change.

File: Nodejs/Product/Nodejs/Intellisense/BufferParser.cs [hunk 1]
```diff
@@ -259,6 +259,9 @@ class BufferParser : IDisposable {
             protected virtual void Dispose(bool disposing) {
                 if (!disposedValue) {
                     if (disposing) {
+                        foreach (var buffer in _buffers.ToArray())
+                            RemoveBuffer(buffer);
```
Comment (mousetraps) [inline Nodejs/Product/Nodejs/Intellisense/BufferParser.cs]: nit: braces

**Comment by mousetraps** [comment]
minor comment and :+1: after that
