### PR TITLE
Fix function declarations in interactive window

### LINKED ISSUE #1030: Cannot define function in Interactive Window
**Expected:**
image

**Actual:**
image

### PR DESCRIPTION
**Pull request by mjbvz**
#####  Bug
Function declarations are broken in interactive window. The root cause is that we are wrapping them in parens, creating function expressions instead.

##### Fix
Don't wrap function declarations in parens for evaluations.

Closes #1030

### CODE REVIEW

File: Nodejs/Product/Nodejs/visualstudio_nodejs_repl.js [hunk 1]
```diff
@@ -108,7 +108,9 @@ function processRequest(command) {
                 var obj;
                 // function f() { } should return undefined, wrapping it in parens
                 // produces a value, so ignore it if we have a function definition.
-                if (!/^\s*function/.test(command["code"])) {
```
Comment (mjbvz) [inline Nodejs/Product/Nodejs/visualstudio_nodejs_repl.js]: The old regexp would match any var starting with `function`. We only want to not apply wrapping for function declarations that use the function keyword explicitly. If I recall, function keyword in this context can either be  followed by either:

* Space and then identifier
* Paren for argument list (actually, this would make it an function expression but JS has a weird ambiguity about function declarations vs function expressions).
* A `*` for a generator.

File: Nodejs/Product/Nodejs/visualstudio_nodejs_repl.js [hunk 2]
```diff
@@ -120,8 +122,6 @@ function processRequest(command) {
                             throw err;
                         }
                     }
-                } else {
-                    obj = vm.runInContext(evalPrefix + '(' + command["code"] + ')', context);
```
Comment (mousetraps) [inline Nodejs/Product/Nodejs/visualstudio_nodejs_repl.js]: Looks like the parens were introduced in #876 - do you remember if there was a reason for them?

**Comment by mousetraps** [comment]
:+1:

File: Nodejs/Product/Nodejs/visualstudio_nodejs_repl.js (hunk 2 above)
Comment (mjbvz) [inline Nodejs/Product/Nodejs/visualstudio_nodejs_repl.js]: Methinks that month-ago @mjbvz was suffering from a bad case of the copy-pastes. 

Questions to ask with any introduced regression like this: why wasn't this caught sooner and how can we prevent this same mistake from happening again. Adding tests is an important step in addressing both of those questions, so I've opened #1063 to track this work.
