### PR TITLE
Debugger connection retry logic

### LINKED ISSUE #245: Running/debugging does not work with x64 version of io.js (but does with x86)
I spent a few hours trying to figure out why debugging doesn't work with io.js despite the [wiki documentation](https://github.com/Microsoft/nodejstools/wiki/io.js-and-ES6-support) saying that it should. Turns out you can't use the x64 version. It *might* launch the first time and run. But you'll never hit a breakpoint or anything. The x86 version works just as you would imagine.

Is this a bug? Expected behavior? Should we update the documentation?

Using:
* io.js 2.3.2 (x86 and x64): https://iojs.org/dist/v2.3.2/
* NTVS 1.1 Beta: https://nodejstools.codeplex.com/releases/view/614706
* Visual Studio 2013 Ultimate - Update 4 (non-elevated)

Thank you for this awesome tool!

### PR DESCRIPTION
**Pull request by billti**
This adds retry logic when attempting to connect to the debug port on Node, in an attempt to resolve #245 and #246.

In some scenarios, especially when using Debug builds of Node/io.js, the Node process doesn't open the debug port (5858 by default) in time. At the network level, this results in the connection being refused. This change adds retry logic if the connection fails (and additional logging).

On my machine, using the 'Debug' build of the latest io.js branch (as using 'Release' shows no issue at all), I can now see the connection retry and succeed, e.g.

```
[17:20:09.0841895] AD7Engine Created (63760528)
[17:20:09.0907085] AD7Engine Called SetRegistryRoot
[17:20:09.0912082] AD7Engine Called SetLocale
[17:20:09.0947085] AD7Engine LaunchSuspended Called with flags 'LAUNCH_ENABLE_ENC' (63760528)
[17:20:09.1791871] Debugger connecting to URI: tcp://localhost:5858/
[17:20:11.2412522] Connection attempt 1 failed with: System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it 127.0.0.1:5858
   at System.Net.Sockets.TcpClient..ctor(String hostname, Int32 port)
   at Microsoft.NodejsTools.Debugger.Communication.NetworkClientFactory.CreateNetworkClient(Uri uri) in C:\src\nodejstools\Nodejs\Product\Nodejs\Debugger\Communication\NetworkClientFactory.cs:line 32
   at Microsoft.NodejsTools.Debugger.Communication.DebuggerConnection.Connect(Uri uri) in C:\src\nodejstools\Nodejs\Product\Nodejs\Debugger\Communication\DebuggerConnection.cs:line 130
[17:20:12.9912323] Debugger connected successfully
[17:20:12.9912323] DebuggerConnection: Request: {"command":"scripts","seq":1,"type":"request","arguments":{"includeSource":false}}
```

Note that on a retry connect, sometime the debugger enters a state where it doesn't appear to be connected, but using "Debug / Break all" will then break on the first line and debugging can then continue. This needs to be looked at separately.

### CODE REVIEW

File: Nodejs/Product/Nodejs/Debugger/Communication/DebuggerConnection.cs [hunk 1]
```diff
@@ -112,10 +112,53 @@ sealed class DebuggerConnection : IDebuggerConnection {
...
+                        {
+                            LiveLogger.WriteLine("Debugger connected successfully");
+                            break;
+                        }
+                        else
+                        {
+                            throw new SocketException();
+                        }
+                    }
+                    catch (Exception ex)
```
Comment (paulvanbrenk) [inline Nodejs/Product/Nodejs/Debugger/Communication/DebuggerConnection.cs]: Do you expect any other exceptions than the SocketException you throw? If not, just filter this on that type and let the other exceptions naturally bubble up, this will preserve the stack better.

Comment (paulvanbrenk) [inline Nodejs/Product/Nodejs/Debugger/Communication/DebuggerConnection.cs]: Since you're not using the exception you should remove the 'ex' variable.

Comment (billti) [inline Nodejs/Product/Nodejs/Debugger/Communication/DebuggerConnection.cs]: I am using it in the WriteLine call immediately below.

Comment (billti) [inline Nodejs/Product/Nodejs/Debugger/Communication/DebuggerConnection.cs]: And yes, I do expect other exceptions. In fact, per the comment above the condition, I don't expect to have to throw the exception myself, that's just for safety. In general any exception trying to connect should cause either a retry or a rethrow after the max retries.

Comment (paulvanbrenk) [inline Nodejs/Product/Nodejs/Debugger/Communication/DebuggerConnection.cs]: In that case, I would add a message to the SocketException you throw to indicate that a networkclient was successfully created but not connected. That way we can investigate further if that happens.

Comment (billti) [inline Nodejs/Product/Nodejs/Debugger/Communication/DebuggerConnection.cs]: Yup, was going to do that, but there is no SocketException constructor that takes a string, and the Message property is read-only. ( https://msdn.microsoft.com/en-us/library/system.net.sockets.socketexception.socketexception(v=vs.110).aspx )

File: Nodejs/Product/Nodejs/Debugger/Communication/DebuggerConnection.cs [hunk 2]
```diff
@@ -112,10 +112,53 @@ sealed class DebuggerConnection : IDebuggerConnection {
...
             Utilities.ArgumentNotNull("uri", uri);
+            LiveLogger.WriteLine("Debugger connecting to URI: {0}", uri);
 
             Close();
             lock (_networkClientLock) {
-                _networkClient = _networkClientFactory.CreateNetworkClient(uri);
+                int connection_attempts = 0;
+                const int MAX_ATTEMPTS = 5;
+                while (true)
+                {
```
Comment (mousetraps) [inline Nodejs/Product/Nodejs/Debugger/Communication/DebuggerConnection.cs]: braces on same line here and everywhere else.

File: Nodejs/Product/Nodejs/Debugger/Communication/DebuggerConnection.cs (hunk 1 above)
Comment (mousetraps) [inline Nodejs/Product/Nodejs/Debugger/Communication/DebuggerConnection.cs]: I don't expect it to be an issue in ths case, but in general we don't want to swallow critical exceptions. 
https://github.com/Microsoft/nodejstools/blob/35817ffdaa1797f95628a22f588fc3ed885f884b/Common/Product/SharedProject/ExceptionExtensions.cs#L23-L29

File: Nodejs/Product/Nodejs/Debugger/Communication/DebuggerConnection.cs [hunk 3]
```diff
@@ -112,10 +112,53 @@ sealed class DebuggerConnection : IDebuggerConnection {
...
+                        {
+                            throw;
+                        }
+                        else
+                        {
+                            // See above TODO. This should be moved off the UI thread or posted to retry
+                            // without blocking in the meantime. For now, this seems the lesser of two
+                            // evils. (The other being the debugger failing to attach on launch if the
+                            // debuggee socket wasn't open quickly enough).
+                            System.Threading.Thread.Sleep(200);
```
Comment (mousetraps) [inline Nodejs/Product/Nodejs/Debugger/Communication/DebuggerConnection.cs]: I'm fine taking this for RC2, but let's file an issue on this since we really shouldn't be blocking.

File: Nodejs/Product/Nodejs/Debugger/DebugEngine/Remote/NodeRemoteEnumDebugProcesses.cs [hunk 4]
```diff
@@ -103,18 +103,24 @@ public NodeRemoteEnumDebugProcesses(NodeRemoteEnumDebugProcesses processes)
...
+                    LiveLogger.WriteLine("IOException connecting to remote debugger");
                     exception = ex;
                 } catch (SocketException ex) {
+                    LiveLogger.WriteLine("SocketException connecting to remote debugger");
                     exception = ex;
                 } catch (WebSocketException ex) {
+                    LiveLogger.WriteLine("WebSocketException connecting to remote debugger");
                     exception = ex;
                 } catch (PlatformNotSupportedException) {
+                    LiveLogger.WriteLine("NodeRemoteEnumDebugProcesses ping timed out.");
```
Comment (mousetraps) [inline Nodejs/Product/Nodejs/Debugger/DebugEngine/Remote/NodeRemoteEnumDebugProcesses.cs]: PlatformNotSupportedException doesn't have anything to do with the ping timing out, does it?

File: Nodejs/Product/Nodejs/Debugger/DebugEngine/Remote/NodeRemoteEnumDebugProcesses.cs [hunk 5]
```diff
@@ -103,18 +103,24 @@ public NodeRemoteEnumDebugProcesses(NodeRemoteEnumDebugProcesses processes)
                         break;
                     }
                 } catch (OperationCanceledException) {
-                    LiveLogger.WriteLine("NodeRemoteEnumDebugProcesses ping timed out.");
+                    LiveLogger.WriteLine("OperationCanceledException connecting to remote debugger");
```
Comment (mousetraps) [inline Nodejs/Product/Nodejs/Debugger/DebugEngine/Remote/NodeRemoteEnumDebugProcesses.cs]: We included the "ping timed out" before to make it clearer what the core issue actually was. Don't mind including the exception as well, but we should also include the ping timeout bit.

**Comment by mousetraps** [comment]
some minor comments and lgtm after that

File: Nodejs/Product/Nodejs/Debugger/Communication/DebuggerConnection.cs (hunk 3 above)
Comment (billti) [inline Nodejs/Product/Nodejs/Debugger/Communication/DebuggerConnection.cs]: Yeah, but as noted above, just the existing TCP connection call blocks for 2 to 3 seconds already trying to connect. Getting this whole logic off the UI thread, or moving to async, seems desirable, but that's a much more invasive change at this point.

Comment (mousetraps) [inline Nodejs/Product/Nodejs/Debugger/Communication/DebuggerConnection.cs]: gotcha, makes sense

**Comment by mousetraps** [comment]
:+1:
