### PR TITLE
#70 Visual Studio crashes when I quit debugging

### LINKED ISSUE #70: Visual Studio crashes when I quit debugging
I'm running Visual Studio 2013 Community.  I've previously had VS Express 2012 and 2013 (various versions) and tried out VS 2015 Preview and CTP 6 when VS started crashing on me.

Since then I uninstalled all versions of VS, though `\Program Files (x86)\Microsoft Visual Studio X.0\` directories exist for 10, 11, 12, and 14 still.  I then installed VS Community 2013 "fresh" (as fresh as it can be with those lingering files).

I installed NTVS for VS 2013 (after uninstalling it, and then removing `\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Node.js Tools*` manually, since uninstalling did not do it).  Now I can repro this crashing every time with the following steps (before it may have been intermittent?):

Open VS, create a new "Basic Node.js Express 4 Application" project, press F5.  The browser pops up with the expected text.  Close the Browser.  Stop debugging.  VS crashes.

It's quite frustrating.  Until a couple days ago (when I started messing with the Babel package, attempting to get ECMAScript 6 features to work), everything was working great.

Let me know what more information you need.

Thanks!

### PR DESCRIPTION
**Pull request by mousetraps**
- Fix potential NullReferenceExceptions

fix #70

### CODE REVIEW

File: Nodejs/Product/Analysis/Analysis/Analyzer/AnalysisUnit.cs [hunk 1]
```diff
@@ -188,9 +188,9 @@ internal AnalysisUnit(JsAst ast, EnvironmentRecord environment)
         }
 
         internal virtual void AnalyzeWorker(DDG ddg, CancellationToken cancel) {
-            if (Tree != ProjectEntry.Tree) {
-                // we were enqueued and a new version became available, don't re-analyze against
-                // the old version.
+            if (Ast != null && ProjectEntry != null && ProjectEntry.Tree != null && Tree != ProjectEntry.Tree) {
```
Comment (billti) [inline Nodejs/Product/Analysis/Analysis/Analyzer/AnalysisUnit.cs]: Should these ever be null? Is it safe to fall through to the remaining code if they are?

**Comment by billti** [comment]
Minor comment, else :+1:

File: Nodejs/Product/Analysis/Analysis/Analyzer/AnalysisUnit.cs (hunk 1 above)
Comment (mousetraps) [inline Nodejs/Product/Analysis/Analysis/Analyzer/AnalysisUnit.cs]: I couldn't reproduce this issue, so I'm not entirely sure (there are null checks for these properties elsewhere in the code, so I presumed it would be safe enough here.) This is something I plan on asking dino today before merging in.

Comment (mousetraps) [inline Nodejs/Product/Analysis/Analysis/Analyzer/AnalysisUnit.cs]: I'm going to at least Assert here, so that we cant catch it in debug builds.

Comment (mousetraps) [inline Nodejs/Product/Analysis/Analysis/Analyzer/AnalysisUnit.cs]: Okay... just reviewed this again with my alter ego from the future, and realized I was being an idiot. I intended to null check and *not* to flow through, and I totally misinterpreted your comment. fixed :smiley:
