### PR TITLE
#530 Fix MEF errors on Jade files

### LINKED ISSUE #530: Error in Visual Studio 2015 Update 1 CTP
Apologies for flagging this if you're not testing in the 2015 Update 1 CTP yet, but I'm getting an error upon opening a Jade file in the editor.  

It seems to be complaining that "contentTypes" is not a key.  Occurs in the constructor for Microsoft.NodejsTools.ClassifierProviderMetadata

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---&gt; System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.&#x000D;&#x000A;   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)&#x000D;&#x000A;   at System.Collections.Immutable.ImmutableDictionary`2.System.Collections.Generic.IDictionary&lt;TKey,TValue&gt;.get_Item(TKey key)&#x000D;&#x000A;   at Microsoft.NodejsTools.ClassifierProviderMetadata..ctor(IDictionary`2 values)&#x000D;&#x000A;   --- End of inner exception stack trace ---&#x000D;&#x000A;   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)&#x000D;&#x000A;   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.MetadataViewClassProvider.CreateProxy(IReadOnlyDictionary`2 metadata, IReadOnlyDictionary`2 defaultValues, Type metadataViewType)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.GetStrongTypedMetadata(IReadOnlyDictionary`2 metadata, Type metadataType)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportElement(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import, RuntimeExport export, Func`3 lazyFactory)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportSite(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.&lt;CreateValue&gt;b__10_0(RuntimeImport import)&#x000D;&#x000A;   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()&#x000D;&#x000A;   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)&#x000D;&#x000A;   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.&lt;&gt;c__DisplayClass15_0.&lt;GetExportedValueHelper&gt;b__0()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.DelegateServices.&lt;&gt;c__DisplayClass2_0`1.&lt;As&gt;b__0()&#x000D;&#x000A;   at System.Lazy`1.CreateValue()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at System.Lazy`1.get_Value()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InvokeMatchingFactories[TExtensionInstance,TExtensionFactory,TMetadataView](IEnumerable`1 lazyFactories, Func`2 getter, IContentType dataContentType, Object errorSource)

### PR DESCRIPTION
**Pull request by billti**
Fixes #530. Not sure what changed in Update1, but apparently this is the MEF pattern to follow, and most importantly - it works. (At least in VS2015 Update1. Still to validate on earlier builds, but this is a common pattern for a while).

### CODE REVIEW

File: Nodejs/Product/Nodejs/Jade/Classifier/JadeClassifierProvider.cs [hunk 1]
```diff
@@ -38,7 +38,7 @@ internal sealed class JadeClassifierProvider : IClassifierProvider {
             ITextBufferFactoryService bufferFact,
             IContentTypeRegistryService contentTypeService,
             [ImportMany(typeof(ITaggerProvider))]Lazy<ITaggerProvider, TaggerProviderMetadata>[] taggerProviders,
-            [ImportMany(typeof(IClassifierProvider))]Lazy<IClassifierProvider, ClassifierProviderMetadata>[] classifierProviders) {
+            [ImportMany(typeof(IClassifierProvider))]Lazy<IClassifierProvider, IContentTypeMetadata>[] classifierProviders) {
```
Comment (mousetraps) [inline Nodejs/Product/Nodejs/Jade/Classifier/JadeClassifierProvider.cs]: nit: how about IClassifierProviderMetadata to keep the naming consistent?

**Comment by mousetraps** [comment]
left a minor comment, but :+1:
